<script lang="ts">
import {base} from '$app/paths';import Frame from './CommunityFrame.svelte';import Story from './CommunityStory.svelte';import Directory from './CommunityDirectory.svelte';import {concept} from '$lib/community/concept';import snapshot from '$lib/community/data.json';import {formatDate} from '$lib/community/channels';
const edition=snapshot.issues[0];const stories=snapshot.stories.filter(s=>s.week===edition.date);const topics=['Engineering','Assurance','Participation','Transition'];let topic=$state('All');let audience=$state('all');let active=$derived(stories.filter(s=>(topic==='All'||s.topic===topic)&&(audience==='all'||s.audiences.includes(audience))));const upcoming=snapshot.items.filter(x=>x.channel==='events'&&x.date>snapshot.asOf).slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3);const recording=snapshot.items.find(x=>x.channel==='recordings');
</script>
<svelte:head><title>{concept.name} · FedRAMP Community</title><meta name="description" content="Weekly perspectives and useful paths into the FedRAMP community."/></svelte:head>
{#snippet issueLink()}<a class="edition-link" href={base+'/community/weekly/'+edition.date+'/'}>Read the September 28 edition <span aria-hidden="true">→</span></a>{/snippet}
{#snippet dates()}<p class="edition-date">Monday, {formatDate(edition.date)} · Covers September 21–27</p>{/snippet}
{#snippet meetings()}<section class="meetings"><h2>Coming together.</h2><p>Upcoming in the October 4 snapshot.</p>{#each upcoming as item (item.id)}<article><time datetime={item.date}>{formatDate(item.date)}</time><h3><a href={base+item.route}>{item.title}</a></h3><p>{item.timing}</p></article>{/each}<a href={base+'/community/events/'}>All events →</a></section>{/snippet}
{#snippet archive()}<nav class="issue-archive" aria-label="Weekly editions"><h2>Previously, in the community.</h2>{#each snapshot.issues.slice(1) as issue (issue.date)}<a href={base+'/community/weekly/'+issue.date+'/'}><time>{formatDate(issue.date)}</time><span>{issue.title} →</span></a>{/each}</nav>{/snippet}
<Frame>
{#if concept.slug==='monday-letter'}
<div class="letter-layout"><aside class="letter-margin"><p>A weekly letter<br/>from the community.</p><span class="sun-stamp" aria-hidden="true"></span><a href="#channels">Find your way in ↓</a></aside><div><header class="opening"><h1>A little context.<br/><em>A clearer week.</em></h1>{@render dates()}<p class="opening-deck">{edition.intro}</p>{@render issueLink()}</header><section class="letter-stories"><h2>This week’s letter</h2>{#each stories as story (story.id)}<Story {story}/>{/each}</section></div></div>{@render meetings()}<Directory compact/>{@render archive()}
{:else if concept.slug==='community-front-page'}
<header class="front-mast"><h1>The community,<br/><em>in focus.</em></h1>{@render dates()}</header><div class="front-layout"><section class="front-lead"><h2>{edition.title}</h2><p class="opening-deck">{edition.intro}</p>{@render issueLink()}<Story story={stories[0]}/></section><section class="front-side"><h2>Also this week</h2>{#each stories.slice(1) as story (story.id)}<Story {story} short/>{/each}</section></div>{@render meetings()}<Directory/>{@render archive()}
{:else if concept.slug==='topic-atlas'}
<header class="atlas-opening"><h1>Follow the ideas.<br/><em>Find the connections.</em></h1><p class="opening-deck">A week of conversations is more useful when you can see what connects them.</p>{@render dates()}{@render issueLink()}</header><div class="atlas-layout"><nav class="topic-rail" aria-label="Topics"><h2>Explore a topic</h2>{#each ['All',...topics] as t (t)}<button aria-pressed={topic===t} onclick={()=>topic=t}>{t==='All'?'The whole week':t}</button>{/each}</nav><section class="atlas-stories" aria-live="polite"><h2>{topic==='All'?'Across the community':topic}</h2>{#each active as story (story.id)}<Story {story}/>{/each}{#if !active.length}<p>No featured story in this topic for this edition. Explore the channel guide below for more.</p>{/if}</section></div><Directory/>{@render archive()}
{:else if concept.slug==='the-briefing'}
<header class="brief-opening"><h1>Your week.<br/><em>Made clearer.</em></h1><div><p class="opening-deck">Four developments to understand. Open the context when you need it.</p>{@render dates()}{@render issueLink()}</div></header><section class="brief-stories"><h2>The short version</h2>{#each stories as story (story.id)}<Story {story} expand/>{/each}</section><Directory compact/>{@render meetings()}{@render archive()}
{:else if concept.slug==='open-house'}
<header class="open-house-opening"><h1>There’s a place<br/>for your <em>perspective.</em></h1><p class="opening-deck">Learn what’s changing. Ask a useful question. Help shape what comes next.</p><nav class="participation-doors" aria-label="Ways to participate"><a href={base+'/community/events/'}>Meet<br/><small>Find a public session →</small></a><a href={base+'/community/rfcs/'}>Contribute<br/><small>Respond to a proposal →</small></a><a href={base+'/community/discussions/'}>Ask<br/><small>Join an open exchange →</small></a></nav></header>{@render meetings()}<section class="house-week"><h2>What brought us here this week.</h2>{@render dates()}<p class="opening-deck">{edition.intro}</p><div class="two-stories">{#each stories as story (story.id)}<Story {story} short/>{/each}</div>{@render issueLink()}</section><Directory compact/>{@render archive()}
{:else if concept.slug==='question-and-context'}
<header class="question-opening"><h1>Good questions<br/><em>move us forward.</em></h1><p class="opening-deck">The useful part of a discussion often comes after the opening post. Start with what people are asking.</p>{@render dates()}{@render issueLink()}</header><section class="questions"><h2>Questions from this week</h2>{#each stories as story (story.id)}<Story {story} question/>{/each}</section><Directory/>{@render archive()}
{:else if concept.slug==='the-week-ahead'}
<header class="agenda-opening"><h1>Look back.<br/><em>Show up.</em><br/>Move forward.</h1><p class="opening-deck">Make room for the conversations that matter.</p></header><div class="agenda-layout"><section><h2>Last complete edition</h2>{@render dates()}{#each stories as story (story.id)}<Story {story} short/>{/each}{@render issueLink()}</section><aside>{@render meetings()}<section class="participate-note"><h2>Make time to respond.</h2><p>Read open proposals and their deadlines before adding formal feedback.</p><a href={base+'/community/rfcs/'}>Explore requests for comment →</a></section></aside></div><Directory compact/>{@render archive()}
{:else if concept.slug==='field-journal'}
<header class="journal-opening"><div class="journal-mark" aria-hidden="true"></div><h1>Notes from<br/><em>the field.</em></h1><p class="opening-deck">The details, questions and small discoveries behind a changing program.</p>{@render dates()}{@render issueLink()}</header><div class="journal-layout"><aside><h2>In this edition</h2>{#each stories as story (story.id)}<a href={'#'+story.id}>{story.title}</a>{/each}</aside><section><h2>{edition.title}</h2>{#each stories as story (story.id)}<Story {story}/>{/each}</section></div><Directory/>{@render archive()}
{:else if concept.slug==='perspectives'}
<header class="perspectives-opening"><h1>See the week<br/>through <em>your work.</em></h1><p class="opening-deck">One shared conversation, with different reasons to pay attention.</p>{@render dates()}{@render issueLink()}</header><section class="perspective-section"><h2>What matters to you?</h2><div class="audience-switch" role="group" aria-label="Audience perspective">{#each [['all','Everyone'],['providers','Providers'],['agencies','Agencies'],['assessors','Assessors']] as pair (pair[0])}<button aria-pressed={audience===pair[0]} onclick={()=>audience=pair[0]}>{pair[1]}</button>{/each}</div><div class="perspective-stories" aria-live="polite">{#each active as story (story.id)}<Story {story}/>{/each}</div><p>These lenses change emphasis, not the underlying facts.</p></section><Directory/>{@render meetings()}{@render archive()}
{:else}
<header class="change-opening"><h1>Questions.<br/>Responses.<br/><em>What happens next.</em></h1><p class="opening-deck">Follow the documented connections, and see where a conversation is still open.</p>{@render dates()}{@render issueLink()}</header><section class="change-sequence"><h2>A correction you can follow</h2><article><h3>A contributor flags an issue</h3><p>The incident-evaluation page discussion captures a reported documentation problem.</p><a href="https://github.com/FedRAMP/2026/discussions/113">Read the original exchange ↗</a></article><article><h3>A response names a release</h3><p>A September 13 reply identifies the release intended to fix the issue.</p><a href="https://github.com/FedRAMP/2026/discussions/113#discussioncomment-18425469">Read the response ↗</a></article><article><h3>The contributor confirms the result</h3><p>On September 15, the participant reports seeing the change.</p><a href="https://github.com/FedRAMP/2026/discussions/113#discussioncomment-18454761">Read the follow-up ↗</a></article></section><section class="ongoing-stories"><h2>Still worth following</h2>{#each stories as story (story.id)}<Story {story} short/>{/each}</section><Directory compact/>{@render archive()}
{/if}
{#if recording}<section class="recording-feature"><div class="play-symbol" aria-hidden="true">▶</div><div><h2>Take a seat. Catch up.</h2><p>{recording.title} · Meeting held {formatDate(recording.date)}</p><a href={recording.source}>Watch the linked recording on YouTube ↗</a></div><a href={base+'/community/recordings/'}>More recordings →</a></section>{/if}
</Frame>
