<script lang="ts">
import {base} from '$app/paths';import Frame from './CommunityFrame.svelte';import Story from './CommunityStory.svelte';import Activity from './CommunityActivity.svelte';import {concept} from '$lib/community/concept';import {formatDate,channels} from '$lib/community/channels';import snapshot from '$lib/community/data.json';
let {date}=$props<{date:string}>();let issue=$derived(snapshot.issues.find(i=>i.date===date)!);let stories=$derived(snapshot.stories.filter(s=>s.week===date));let records=$derived(snapshot.activity.filter(a=>issue.activityIds.includes(a.id)));let meetings=$derived(snapshot.items.filter(x=>x.channel==='events'&&x.date>=issue.start&&x.date<=issue.end));let recordings=$derived(snapshot.items.filter(x=>x.channel==='recordings'&&x.date>=issue.start&&x.date<=issue.end));let lookAhead=$derived(snapshot.items.filter(x=>x.channel==='events'&&x.date>=date&&x.date<new Date(new Date(date).getTime()+7*864e5).toISOString().slice(0,10)).sort((a,b)=>a.date.localeCompare(b.date)));let publications=$derived(snapshot.items.filter(x=>!['events','recordings','discussions','cr26-discussions'].includes(x.channel)&&x.date>=issue.start&&x.date<=issue.end));let topic=$state('All');let audience=$state('all');let shown=$derived(stories.filter(s=>(topic==='All'||s.topic===topic)&&(audience==='all'||s.audiences.includes(audience))));
</script>
<svelte:head><title>{issue.title} · {formatDate(date)} · FedRAMP Weekly</title></svelte:head>
<Frame><article class="issue-page"><header class="issue-opening"><a href={base+'/community/weekly/'}>← All weekly editions</a><h1>{issue.title}</h1><p class="edition-date">Monday, {formatDate(date)} · Covers {formatDate(issue.start)}–{formatDate(issue.end)} · Eastern Time</p><p class="opening-deck">{issue.intro}</p><p class="small">Reconstructed prototype edition. Sources captured October 4; later replies are excluded from this week’s activity. Source wording may reflect edits made after the week ended.</p></header><div class="issue-body"><aside class="issue-contents"><h2>Inside this edition</h2>{#each shown as s (s.id)}<a href={'#'+s.id}>{s.title}</a>{/each}<a href="#week-activity">All captured activity</a><a href="#week-resources">Meetings & recordings</a></aside><div class="issue-stories">
{#if concept.slug==='topic-atlas'}<div class="audience-switch" role="group" aria-label="Topics">{#each ['All','Engineering','Assurance','Participation','Transition'] as t (t)}<button aria-pressed={topic===t} onclick={()=>topic=t}>{t}</button>{/each}</div>{/if}
{#if concept.slug==='perspectives'}<div class="audience-switch" role="group" aria-label="Audience perspective">{#each [['all','Everyone'],['providers','Providers'],['agencies','Agencies'],['assessors','Assessors']] as p (p[0])}<button aria-pressed={audience===p[0]} onclick={()=>audience=p[0]}>{p[1]}</button>{/each}</div>{/if}
{#each shown as story (story.id)}<Story {story} expand={concept.slug==='the-briefing'} question={concept.slug==='question-and-context'}/>{/each}{#if !shown.length}<p>No featured stories match this view. Choose another perspective.</p>{/if}
<section class="week-resources" id="week-resources"><h2>Meetings & recordings</h2>{#if meetings.length}{#each meetings as item (item.id)}<p><a href={item.source}>{item.title}</a> · {formatDate(item.date)}</p>{/each}{:else}<p>No meetings were captured for this week.</p>{/if}{#each recordings as item (item.id)}<p><a href={item.source}>Watch: {item.title} ↗</a></p>{/each}<p class="small">Recording dates refer to the meeting; upload dates were not supplied.</p></section>
{#if publications.length}<section class="week-publications"><h2>Also published this week</h2>{#each publications as item (item.id)}<article><h3><a href={base+item.route}>{item.title}</a></h3><p>{item.summary}</p></article>{/each}</section>{/if}<section class="quiet-note"><h2>Across the other channels</h2><p>{#if issue.quietChannels.length}No new items were captured this week for {issue.quietChannels.map(c=>channels.find(x=>x.id===c)?.name).join(', ')}. Their earlier material remains available in the channel guide.{:else}Additional publications are listed in the complete weekly activity below.{/if}</p><a href={base+'/community/#channels'}>Explore all channels →</a></section>
{#if lookAhead.length}<section class="week-lookahead"><h2>Looking ahead from this edition</h2>{#each lookAhead as item (item.id)}<p><a href={item.source}>{item.title}</a> · {formatDate(item.date)}</p>{/each}<p class="small">A separate preview of the following week, based on the saved event schedule.</p></section>{/if}
</div></div><section class="all-week" id="week-activity"><h2>The complete captured week</h2><p>Publications, meetings, new discussions, comments and edits. Short acknowledgments remain here even when they are not featured in the editorial summary.</p><details class="activity-disclosure"><summary>Browse all {records.length} captured records</summary><Activity {records}/></details></section></article></Frame>
