<script lang="ts">
  import { asset, resolve } from '$lib/utils/paths';

  interface Event {
    id: string;
    title: string;
    startDatetime: string;
    endDatetime: string;
    /**
     * ID of this specific occurrence, e.g. "rev5-cwg-2026-09-02". Generated by
     * `expandEventOccurrences` from the same date that `event/[eventId]/+page.ts`
     * uses to prerender pages, so it is guaranteed to resolve to a real route.
     */
    occurrenceId?: string;
  }

  let { events = [] }: { events: Event[] } = $props();

  const TIME_ZONE = 'America/New_York';
  const TIME_FORMAT: Intl.DateTimeFormatOptions = {
    timeZone: TIME_ZONE,
    hour: '2-digit',
    minute: '2-digit'
  };

  function formatTime(dateTime: string): string {
    return new Date(dateTime).toLocaleTimeString('en-US', TIME_FORMAT);
  }

  function formatDate(dateTime: string): { month: string; day: string } {
    const date = new Date(dateTime);
    const month = date.toLocaleDateString('en-US', { month: 'short' }).toUpperCase();
    const day = date.toLocaleDateString('en-US', { day: 'numeric' });
    return { month, day };
  }

  function getEventDetailsUrl(event: Event): string {
    return resolve(`/event/${event.occurrenceId || event.id}`);
  }
</script>

<div class="events-widget">
  <h3 class="events-widget__title">Upcoming Events</h3>

  {#if events.length === 0}
    <p class="events-widget__empty">No upcoming events scheduled.</p>
  {:else}
    {#each events as event, index (index)}
      {@const { month, day } = formatDate(event.startDatetime)}
      <article class="event-entry">
        <div class="event-entry__date">
          <span class="event-entry__month">{month}</span>
          <span class="event-entry__day">{day}</span>
        </div>

        <div class="event-entry__details">
          <h4 class="event-entry__title">{event.title}</h4>
          <div class="event-entry__info">
            <time class="event-entry__time">
              {formatTime(event.startDatetime)} - {formatTime(event.endDatetime)} ET
            </time>
            <a class="event-entry__link" href={getEventDetailsUrl(event)} aria-label="View details for {event.title}">
              Event Details
              <svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
                <use href={asset('/uswds/img/sprite.svg#arrow_forward')}></use>
              </svg>
            </a>
          </div>
        </div>
      </article>
    {/each}
  {/if}
</div>

<style lang="scss">
  @use '@styles/uswds.scss' as uswds;

  .events-widget {
    background: uswds.color('primary');
    padding: 17px 30px;

    &__title {
      margin: 0;
    }

    &__empty {
      color: uswds.color('base-lighter');
    }
  }

  .event-entry {
    display: flex;
    flex-direction: row;
    margin-top: 15px;
    padding-bottom: 15px;
    border-bottom: 2px solid #2a1b37;

    &__date {
      display: flex;
      flex-direction: column;
      align-items: center;
    }

    &__month {
      font-size: 1rem;
      font-weight: uswds.font-weight('bold');
    }

    &__day {
      font-size: 1.35rem;
      font-weight: uswds.font-weight('bold');
    }

    &__details {
      margin-left: 25px;
      flex: 1;
    }

    &__title {
      margin: 0;
      font-size: 1.5rem;
    }

    &__info {
      display: flex;
      justify-content: space-between;
      align-items: center;
      @media (max-width:  #{uswds.units('desktop') - 0.01rem}) {
        flex-direction: column;
        align-items: flex-start;
      }
    }

    &__time {
      display: block;
    }

    &__link {
      color: uswds.color('accent-warm-light');
      position: relative;
      vertical-align: middle;
      text-decoration: none;

      .usa-icon {
        vertical-align: middle;
      }

      &:hover,
      &:focus {
        color: uswds.color('accent-warm-light');
      }

      &::after {
        content: '';
        position: absolute;
        width: 98%;
        height: 0;
        left: 0;
        bottom: 4px;
        border-bottom: 1px solid uswds.color('accent-warm-light');
      }
    }
  }
</style>
